/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package aguilar_fcojavierA;
//Importamos las herramientas necesarias para nuestro codigo.
import Clases_Herramientas.Profesor;
import Clases_Herramientas.Persona;
import Clases_Herramientas.Alumno;
import Clases_Herramientas.Asignatura;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Javi.OH
 */
public class ApartadoAProfesor extends javax.swing.JFrame {

    /**
     * Creates new form ApartadoAProfesor
     */
    Profesor profe; // Creamos la variable profesor para almacenar los valores que se nos pasen en el formulario
    int pos; //Variable que almacena la posicion del array de profesores
    Profesor listaP[] = new Profesor[100]; //Creamos un array de profesores con 100 por defecto

    public ApartadoAProfesor() {
        initComponents();
        this.pos = 0; //Inicializamos nuestro contador a 0
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Insertar = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Nombre = new javax.swing.JTextField();
        DNI = new javax.swing.JTextField();
        Sueldo = new javax.swing.JTextField();
        Direccion = new javax.swing.JTextField();
        Estudios = new javax.swing.JComboBox<>();
        NombreT = new javax.swing.JLabel();
        DNIT = new javax.swing.JLabel();
        SueldoT = new javax.swing.JLabel();
        EstudiosT = new javax.swing.JLabel();
        DireccionT = new javax.swing.JLabel();
        TablaDatos = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Sexo = new javax.swing.JLabel();
        SexoS = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Insertar.setText("Insertar");
        Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InsertarActionPerformed(evt);
            }
        });

        Eliminar.setText("Eliminar");
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });

        Estudios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Doctorado", "Postgrado", "Universitario", "FP Superior", "Bachillerato", "FP Medio" }));

        NombreT.setText("Nombre");

        DNIT.setText("DNI");

        SueldoT.setText("Sueldo");

        EstudiosT.setText("Estudios");

        DireccionT.setText("Direccion");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DNI", "Nombre", "Estudios", "Direccion", "Sueldo", "Sexo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TablaDatos.setViewportView(Tabla);
        if (Tabla.getColumnModel().getColumnCount() > 0) {
            Tabla.getColumnModel().getColumn(0).setResizable(false);
            Tabla.getColumnModel().getColumn(1).setResizable(false);
            Tabla.getColumnModel().getColumn(2).setResizable(false);
            Tabla.getColumnModel().getColumn(3).setResizable(false);
            Tabla.getColumnModel().getColumn(4).setResizable(false);
            Tabla.getColumnModel().getColumn(5).setResizable(false);
        }

        Sexo.setText("Sexo");

        SexoS.setText("Masculino");
        SexoS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexoSActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(Eliminar)))
                .addGap(174, 174, 174))
            .addGroup(layout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(DireccionT)
                            .addComponent(NombreT)
                            .addComponent(DNIT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(EstudiosT))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(SueldoT)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estudios, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sexo)
                        .addGap(95, 95, 95)
                        .addComponent(SexoS, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Sueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NombreT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SueldoT))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DNI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Estudios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DNIT)
                    .addComponent(EstudiosT))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionT, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexoS, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Insertar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(TablaDatos, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(236, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertarActionPerformed
        if (DNI.getText().length() > 0 && Nombre.getText().length() > 0 && Direccion.getText().length() > 0 && Sueldo.getText().length() > 0) {
            //Utilizamos este if para controlar que los campos de los datos a introducir estén rellenos, para que no de error en caso de no introducir ningun dato.
            try {
                double dinero = Double.parseDouble(Sueldo.getText()); // Con esta línea de código convertimos un String, el sueldo, a double.
                this.profe = new Profesor(Nombre.getText(), Direccion.getText(), DNI.getText(), SexoS.isSelected(), dinero, Estudios.getSelectedItem().toString());
                //Creamos un profesor con los datos que se nos pasan por el formulario.
                listaP[this.pos] = this.profe;
                //Agregamos al profesor creado en la lista de profesores.
                this.pos++; //Incrementamos el contador en 1.
                //Tocamos el modelo de la tabla
                DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
                modelo.addRow(new Object[]{DNI.getText(), Nombre.getText(), Estudios.getSelectedItem().toString(), Direccion.getText(), dinero, SexoS.getText()});
                //Reestablecemos todos los campos.
                DNI.setText(""); //
                Nombre.setText("");
                Direccion.setText("");
                Sueldo.setText("");
                SexoS.setSelected(false);
                SexoS.setText("Masculino");
                Estudios.setSelectedIndex(0); 
            } catch (RuntimeException e) {
                JOptionPane.showMessageDialog(this, "ERROR: El sueldo introducido es incorrecto.", "ERROR", JOptionPane.ERROR_MESSAGE);
                //Con este catch controlamos que el usuario no pueda introducir un sueldo incorrecto. 
            }
        } else {
            JOptionPane.showMessageDialog(this, "ERROR: Complete todos los campos, por favor.", "ERROR", JOptionPane.ERROR_MESSAGE);
            //Mensaje de error que se muestra en caso de que el usuario no complete alguno de los campos
        }
    }//GEN-LAST:event_InsertarActionPerformed

    private void SexoSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexoSActionPerformed
        if (!SexoS.isSelected()) {
            SexoS.setText("Masculino");
        } else {
            SexoS.setText("Femenino");
        }
        //Esta estructura if else la utilizamos para modificar el texto que aparece en el boton en funcion de si esta pulsado o no.
    }//GEN-LAST:event_SexoSActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
        try {
            int fila = Tabla.getSelectedRow();
            DefaultTableModel modelo = (DefaultTableModel) Tabla.getModel();
            modelo.removeRow(fila);
            this.listaP[fila] = null;
        } catch (RuntimeException e) {
            JOptionPane.showMessageDialog(this, "ERROR: Debe seleccionar una fila para eliminarla.", "ERROR", JOptionPane.ERROR_MESSAGE);
            //Este catch nos ayuda a controlar la posibilidad de que el usuario no seleccione ninguna filapara ser borrada.
        }
    }//GEN-LAST:event_EliminarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ApartadoAProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ApartadoAProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ApartadoAProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ApartadoAProfesor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ApartadoAProfesor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DNI;
    private javax.swing.JLabel DNIT;
    private javax.swing.JTextField Direccion;
    private javax.swing.JLabel DireccionT;
    private javax.swing.JButton Eliminar;
    private javax.swing.JComboBox<String> Estudios;
    private javax.swing.JLabel EstudiosT;
    private javax.swing.JButton Insertar;
    private javax.swing.JTextField Nombre;
    private javax.swing.JLabel NombreT;
    private javax.swing.JLabel Sexo;
    private javax.swing.JToggleButton SexoS;
    private javax.swing.JTextField Sueldo;
    private javax.swing.JLabel SueldoT;
    private javax.swing.JTable Tabla;
    private javax.swing.JScrollPane TablaDatos;
    // End of variables declaration//GEN-END:variables
}
